server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: meme-service-route
              uri: lb://meme-service
              predicates:
                - Path=/api/v1/memes/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  gateway:
    enabled: true