server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          enabled: true
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**

            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/user-service/v3/api-docs/**


# Configuração do Swagger UI
springdoc:
  swagger-ui:
    urls:
      - name: "User Service"
        url: /user-service/v3/api-docs
    disable-swagger-default-url: true

# Configuração do Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true
    disable-delta: true
  instance:
    prefer-ip-address: true

# Monitoramento e Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: TRACE