spring:
  application:
    name: discoveryserverapp

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:

    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: ${spring.application.name}
    description: "Serviço de descoberta de microserviços"
    version: "1.0.0-SNAPSHOT"
  contact:
    email: "suporte@nca.com.br"
    department: "Desenvolvimento"